### ISSUE TITLE
Prefix all with BrowserExt and the object name

### ISSUE THREAD

**Issue by frivoal** [browserext/browserext#10]
**This is a tentative resolution of the CG. If no dissenting opinion is expressed here within 10 days, this will be considered the consensus of the CG. Work on this item may begin before the 10 days are elapsed, but any such work will be rescinded if the eventual consensus disagrees with this tentative resolution.**

**Comment by frivoal** [comment]
Meeting minutes: http://browserext.github.io/minutes/2016-09-22.html#resolution03

**Comment by snoack** [comment]
How about moving all names into the `browser` namespace, rather than prefixing them? Isn't that what namespaces are for in the first place? Which names exist anyway that aren't in that namespace yet?

**Comment by frivoal** [comment]
This is about prefixing abstract interface names and type names, not the actual objects, which will indeed be living in the browser namespace.
