### ISSUE TITLE
Spec should use keywords MUST, MAY, SHALL according to RFC 2119

### ISSUE THREAD

**Issue by mikepie1** [browserext/browserext#15]
See https://dev.w3.org/2008/video/mediaann/ReSpec.js/documentation.html

**Comment by frivoal** [comment]
The corresponding Pull request for this issue can be merged:

**This is a tentative resolution of the CG. If no dissenting opinion is expressed here within 10 days, this will be considered the consensus of the CG. Work on this item may begin before the 10 days are elapsed, but any such work will be rescinded if the eventual consensus disagrees with this tentative resolution.**

**Comment by frivoal** [comment]
http://browserext.github.io/minutes/2017-02-02.html#resolution00

**Comment by mikepie1** [comment]
Note to self... make sure each use of the words MAY, MUST specify the WHO (browser vendor, extension developer, user, etc).

**Comment by mikepie1** [comment]
Discussed during 2017.02.15 meeting. No dissenting opinion was expressed within 10 days. Closing.
