### ISSUE TITLE
Spec <section> tags should use correct normative/informative(non-normative) class 

### ISSUE THREAD

**Issue by mikepie1** [browserext/browserext#16]
Current spec is inconsistent in matching the intent of the section with its tag

**Comment by frivoal** [comment]
The corresponding Pull request for this issue can be merged:

**This is a tentative resolution of the CG. If no dissenting opinion is expressed here within 10 days, this will be considered the consensus of the CG. Work on this item may begin before the 10 days are elapsed, but any such work will be rescinded if the eventual consensus disagrees with this tentative resolution.**

**Comment by frivoal** [comment]
http://browserext.github.io/minutes/2017-02-02.html#resolution01

**Comment by mikepie1** [comment]
Closing. This was addressed with PR https://github.com/browserext/browserext/pull/44 
We can open new issues if this is insufficient.
