### ISSUE TITLE
Top level object and protocol names.

### ISSUE THREAD

**Issue by frivoal** [browserext/browserext#2]
The top level object to which extension related APIs should be attached will be called `browser`, and the protocol name for urls will be `browserext://`.

Alternatives considered included `extension`, `nex`, `navigator.extension`, `extension://`, `nex://`, `browser-extension://`, but most preferred the two above.

For compatibility reasons, aliasing `browser` to `chrome` may be necessary.

**This is a tentative resolution of the CG. If no dissenting opinion is expressed here within 10 days, this will be considered the consensus of the CG. Work on this item may begin before the 10 days are elapsed, but any such work will be rescinded if the eventual consensus disagrees with this tentative resolution.**

**Comment by frivoal** [comment]
@shwetank, since you had reservations, I would appreciate if you could explicitly let us know if you can live with this resolution.

**Comment by shwetank** [comment]
Hi,

I preferred .nex as the packaging format name, but was quite open to url schema for referring for extensions. 

I see that the github issue is already resolved (sorry for not chiming in on time), but anyways, what was the problem with browser-extension:// as a url schema? 

As for top level object, I still think navigator.extension.\* works better. Developers are already used to such a naming scheme on the navigator object (its the object most suited for getting identity info and state information about the browser) so I don't think the verbosity argument is convincing me as many devs use the navigator object all the time.

However, if all others have set their sights on browser as a top level object, then okay I guess :)

Regards,

**Comment by frivoal** [comment]
> what was the problem with browser-extension:// as a url schema? 

Mostly that it felt too long. This is a subjective call, but that's the one that pleased most people.

> As for top level object [...] However, if all others have set their sights on browser as a top level object, then okay I guess :)

Right, that too is a subjective call, but it was the preferred choice of everyone other than you. Thanks for your understanding.
