### ISSUE TITLE
Define how insertions, @@patters, and other string parsing works for i18n

### ISSUE THREAD

**Issue by mikepie1** [browserext/browserext#24]

**Comment by kmaglione** [comment]
Some details about the way this currently works in Chrome and Firefox:

# Locale Files

This is the comment in our locale loading code that describes how substitutions are handled:

``` js
    // Chrome does not document the semantics of its localization
    // system very well. It handles replacements by pre-processing
    // messages, replacing |$[a-zA-Z0-9@_]+$| tokens with the value of their
    // replacements. Later, it processes the resulting string for
    // |$[0-9]| replacements.
    //
    // Again, it does not document this, but it accepts any number
    // of sequential |$|s, and replaces them with that number minus
    // 1. It also accepts |$| followed by any number of sequential
    // digits, but refuses to process a localized string which
    // provides more than 9 substitutions.
```

# Locale Codes and Matching

Locale codes used in file/directory names and returned by the API, contrary to accepted standards, are in the form: `<language> ["_" <region>]` which is to say, a two-letter language code, optionally followed by an underscore and a two-letter region code. [Standards](https://tools.ietf.org/html/rfc5646) would dictate a language code, optionally followed by a hyphen and region code, optionally followed by a hyphen and variant name. Which, ideally, we should support. But Chrome does not.

Locale codes are matched such that an exact match is used if available, falling back to the least-specific, closest match. Therefore, for "en-US", the following locales would be chosen, in order of preference:
- en-US
- en-US-var
- en
- en-GB
- en-GB-var
- <default locale>

# Locale Message Replacement

Locale messages in the form `__MSG_<message name>__` are automatically replaced with the appropriate localized message in CSS files and certain `manifest.json` string values.

Specifically, the replacements are done according to the regular expression `__MSG_([A-Za-z0-9@_]+?)__`, meaning that the first occurrence of `__` terminates the message name immediately.

CSS files are pre-processed as a raw text stream, with no considerations for CSS syntax.

`manifest.json` values are processed _after_ the JSON has been parsed, and the results are always treated as literal strings. The following manifest keys are processed for localization messges:
- `name`
- `short_name`
- `description`
- `author`
- `homepage_url`
- `developer.name`
- `developer.url`
- `browser_action.default_title`
- `browser_action.default_url` (not localized in Chrome)
- `page_action.default_title`
- `page_action.default_url` (not localized in Chrome)

# Additional Resources

This is documented in some more (though in some cases less technical) detail at:

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/i18n/Locale-Specific_Message_reference

**Comment by frivoal** [comment]
As per the [2017-02-02 teleconf](http://browserext.github.io/minutes/2017-02-02.html#action02), this should be moved to a separate section, not under the manifest. The pull request can be merged, but the sections should be reorganized.

**Comment by mikepie1** [comment]
Closing. This was addressed with PR https://github.com/browserext/browserext/pull/44 
We can open new issues if this is insufficient.
