### ISSUE TITLE
Discuss adding runtime.lastError and onInstalled

### ISSUE THREAD

**Issue by mikepie1** [browserext/browserext#25]

**Comment by snoack** [comment]
If we are going with promises and omit the legacy calling convention using callbacks from the spec (see #38), we wouldn't need `runtime.lastError` for errors in asynchronous methods. However, @Rob--W mentioned in #12, that some event listeners have to handle errors too. @kmaglione suggested that we could pass the error as argument there instead. I agree that this would be nicer, but perhaps not worth a departure from what is currently implemented by browsers and used by existing extensions.

**Comment by mikepie1** [comment]
Per meeting http://browserext.github.io/minutes/2016-10-20.html decided to keep onInstalled but not lastError. Spec upadated in Pull Request 44 https://github.com/browserext/browserext/pull/44
