### ISSUE TITLE
Define how and where manifest.json "permissions" url patterns are applied/used

### ISSUE THREAD

**Issue by mikepie1** [browserext/browserext#28]

**Comment by scottlow** [comment]
Note: Ensure that the effect of host permissions on cross-origin requests is captured in the spec. See https://developer.chrome.com/extensions/xhr for more information.

**Comment by mikepie1** [comment]
Closing. This was addressed with PR https://github.com/browserext/browserext/pull/44 
We can open new issues if this is insufficient.
