### ISSUE TITLE
Discuss adding "extensionId" or "extensionName" property in addition to "title" for WebDriver

### ISSUE THREAD

**Issue by mikepie1** [browserext/browserext#31]

**Comment by mikepie1** [comment]
Discussed during 2017.02.15 meeting. Closing.

**Comment by frivoal** [comment]
”Add the name property, and define it to be the default locale.”

**This is a tentative resolution of the CG. If no dissenting opinion is expressed here within 10 days, this will be considered the consensus of the CG. Work on this item may begin before the 10 days are elapsed, but any such work will be rescinded if the eventual consensus disagrees with this tentative resolution.**

**Comment by frivoal** [comment]
See http://browserext.github.io/minutes/2017-02-16.html#resolution01
