### ISSUE TITLE
Add more support for contextMenu in WebDriver

### ISSUE THREAD

**Issue by mikepie1** [browserext/browserext#33]
radio, checkbox, checkstate, groups, enable/disable, item type (separator, submenu, item)

**Comment by frivoal** [comment]
As per the [2017-02-02 teleconf](http://browserext.github.io/minutes/2017-02-02.html#action03), Action on @kmaglione to review if this is complete and sufficient.

**Comment by mikepie1** [comment]
Closing. I made additional changes per @kmaglione feedback in 2017.02.02 meeting. @kmaglione to open new issues if needed. http://browserext.github.io/minutes/2017-02-02.html
This was addressed with PR https://github.com/browserext/browserext/pull/44
